thumb_tip:
  enable: True
  config: /etc/xela/thumb.ini
  ip: 127.0.0.1
  port: 5000

index_tip:
  enable: True
  config: /home/handlingteam2/HASA/ros_ws/src/xela_package/xela_server_ros/config/index.ini
  ip: 127.0.0.1
  port: 5050

middle_tip:
  enable: True
  config: /etc/xela/middle.ini
  ip: 127.0.0.1
  port: 5100

ring_tip:
  enable: True
  config: /home/handlingteam2/HASA/ros_ws/src/xela_package/xela_server_ros/config/ring.ini
  ip: 127.0.0.1
  port: 5150