index_tip:
  enable: True
  config: /etc/xela/index.ini
  ip: 127.0.0.1
  port: 5050

middle_tip:
  enable: False
  config: /etc/xela/middle.ini
  ip: 127.0.0.1
  port: 5100

ring_tip:
  enable: False
  config: /etc/xela/ring.ini
  ip: 127.0.0.1
  port: 5150

thumb_tip:
  enable: True
  config: /etc/xela/thumb.ini
  ip: 127.0.0.1
  port: 5000